# Generated by Django 4.1.5 on 2024-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_img_url',
            field=models.CharField(default='https://wp.validthemes.net/restan/wp-content/uploads/2024/05/13-1.jpg', max_length=500),
        ),
    ]
