# Generated by Django 4.1.5 on 2024-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApi', '0002_food_food_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_img_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
