# Generated by Django 4.1.5 on 2024-09-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotelApi', '0004_rename_food_type_foodtaste_taste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('No_of_person', models.IntegerField()),
                ('Date', models.DateField()),
                ('time', models.TimeField()),
                ('Booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
