# Generated by Django 5.1.1 on 2024-10-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApi', '0006_food_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelreservation',
            name='No_of_person',
            field=models.CharField(max_length=20),
        ),
    ]
