# Generated by Django 5.1.1 on 2024-11-16 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApi', '0008_cart_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_rating',
        ),
        migrations.AddField(
            model_name='food',
            name='food_rating_average',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='food_rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='food_rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotelApi.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
