# Generated by Django 5.1.1 on 2024-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApi', '0010_alter_food_food_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_rating_sum',
            field=models.IntegerField(default=5),
        ),
    ]
